### PR TITLE
KRACOEUS-8764:fix additional equipment system generated attachments

### PR DESCRIPTION
**Pull request by jwillia**

### CODE REVIEW

**Comment by leoherbie** [comment]
There are several places that could be fixed in s2s.  Lets use a consistent approach for obtaining resources using DI.

Please fix the following files:

RRBudgetBaseGenerator.java
```
Source xsltSource = new StreamSource(getClass().getResourceAsStream("/org/kuali/kra/s2s/stylesheet/AdditionalEquipmentAttachment.xsl"));
```
```
private static final String EXTRA_KEYPERSON_ATTACHMENT_XSL = "/org/kuali/kra/s2s/stylesheet/ExtraKeyPersonAttachment.xsl";
```
RRFedNonFedBudget10V1_1Generator.java

```
Source xsltSource = new StreamSource(getClass().getResourceAsStream("/org/kuali/kra/s2s/stylesheet/AdditionalEquipmentAttachmentNonFed.xsl"));
```
```
private static final String EXTRA_KEYPERSON_ATTACHMENT_NON_FED_XSL = "/org/kuali/kra/s2s/stylesheet/ExtraKeyPersonAttachmentNonFed.xsl";
```
RRFedNonFedBudgetV1_1Generator.java
```
Source xsltSource = new StreamSource(getClass().getResourceAsStream("/org/kuali/kra/s2s/stylesheet/AdditionalEquipmentAttachmentNonFed.xsl"));
```
```
private static final String EXTRA_KEYPERSON_ATTACHMENT_NON_FED_XSL = "/org/kuali/kra/s2s/stylesheet/ExtraKeyPersonAttachmentNonFed.xsl";
```
RRKeyPersonBase.java
```
protected static final String ADDITIONALKEYPERSONPROFILES_XSL = "/org/kuali/kra/s2s/stylesheet/additionalkeypersonprofiles.xsl";
```

**Comment by leoherbie** [comment]
To obtain these resources:

```    @Value("classpath:org/kuali/coeus/s2sgen/impl/generate/support/stylesheet/<STYLESHEET_NAME>.xsl")
private Resource <STYLESHEET_NAME>Stylesheet;
```

Also, provide getters and setters.

**Comment by leoherbie** [comment]
you also wont need any special exception handling because the generator will fail to while spring is wiring it if the resource doesn't exist

**Comment by jwillia** [comment]
updated to use DI, still need the try block as getInputStream throws an IOException

**Pull request merged**
